# Generated by Django 2.2.4 on 2019-09-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0002_question_myid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='state',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
